name: fileglancer-central
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.12
  - fastapi
  - uvicorn
  - sqlalchemy
  - sqlite
  - pydantic
  - pydantic-settings
  - loguru
  - atlassian-python-api
  - ipykernel
  - pytest
  - pytest-cov
