name: zarrcade
services:

    webapp:
        image: ghcr.io/janeliascicomp/fileglancer-central:0.0.1
        ports:
          - 8000
        restart: unless-stopped
        volumes:
          - ${DB_DIR}:/db:rw,shared
        environment:
          - DB_URL=${DB_URL}
          - FGC_CONFLUENCE_TOKEN=${FGC_CONFLUENCE_TOKEN}

    nginx:
        image: nginx
        depends_on:
          - webapp
        ports:
          - 7443:443
        restart: unless-stopped
        volumes:
          - ./nginx.conf:/etc/nginx/conf.d/fileglancer-central.conf
          - ${CERT_FILE}:/certs/default.crt
          - ${KEY_FILE}:/certs/default.key

