name: zarrcade
services:

    webapp:
        image: ghcr.io/janeliascicomp/fileglancer-central:latest
        ports:
          - 7878
        restart: unless-stopped
        volumes:
          - ${DB_DIR}:/db:rw,shared
        environment:
          - DB_URL=${DB_URL}

    nginx:
        image: nginx
        depends_on:
          - webapp
        ports:
          - 80:80
          - 443:443
        restart: unless-stopped
        volumes:
          - $PWD/nginx.conf:/etc/nginx/conf.d/fileglancer-central.conf
          - ${CERT_FILE}:/certs/default.crt
          - ${KEY_FILE}:/certs/default.key

