name: fileglancer
services:

    fileglancer-central:
        image: ghcr.io/janeliascicomp/fileglancer-central:0.2.0
        restart: unless-stopped
        volumes:
          - ${DB_DIR}:/db:rw,shared
        ports:
          - 8989:8000
        environment:
          - ${CONFIG_FILE}:/app/fileglancer-central/config.yaml
          - FGC_CONFLUENCE_TOKEN=${FGC_CONFLUENCE_TOKEN}
          - FGC_JIRA_TOKEN=${FGC_JIRA_TOKEN}

    nginx:
        image: nginx
        # This is needed to access the host machine from within the container
        # so that we can proxy the jupyterhub server.
        extra_hosts:
          - "host.docker.internal:host-gateway"
        ports:
          - 80:80
          - 443:443
        restart: unless-stopped
        volumes:
          - ./nginx.conf:/etc/nginx/conf.d/default.conf
          - ./html:/etc/nginx/html
          - ${CERT_FILE}:/certs/default.crt
          - ${KEY_FILE}:/certs/default.key

    # jupyterhub is installed on bare metal and is not managed with this deployment
    # see the README for more details.
    # jupyterhub:
    #    image:
