name: fileglancer
services:

    fileglancer-central:
        image: ghcr.io/janeliascicomp/fileglancer-central:0.7.2
        restart: unless-stopped
        volumes:
          - ${DB_DIR}:/db:rw,shared
        ports:
          - 8989:8000
        environment:
          - ${CONFIG_FILE}:/app/fileglancer-central/config.yaml
          - FGC_CONFLUENCE_TOKEN=${FGC_CONFLUENCE_TOKEN}
          - FGC_JIRA_TOKEN=${FGC_JIRA_TOKEN}

    # jupyterhub is installed on bare metal and is not managed with this deployment
    # see the README for more details.
    # nginx:
    #    image: nginx
    # jupyterhub is installed on bare metal and is not managed with this deployment
    # see the README for more details.
    # jupyterhub:
    #    image:
